# Generated by Django 3.1.7 on 2021-06-18 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=20)),
                ('father_initials', models.CharField(blank=True, max_length=5)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('study_year', models.CharField(blank=True, max_length=1)),
                ('group', models.CharField(blank=True, max_length=5)),
                ('id_number', models.CharField(blank=True, default=None, max_length=10)),
                ('img', models.CharField(blank=True, default='https://i.ibb.co/tK2fLz6/250px-Nokota-Horses-cropped.jpg', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000)),
                ('question_author', models.CharField(default=None, max_length=100)),
                ('answer', models.TextField(blank=True, max_length=1000)),
                ('only_for_me', models.BooleanField(blank=True, default=False)),
                ('anonymous', models.BooleanField(blank=True, default=False)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('answered', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
