# Generated by Django 3.1.7 on 2021-06-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.CharField(default='https://i.ibb.co/tK2fLz6/250px-Nokota-Horses-cropped.jpg', max_length=100),
        ),
    ]
