# Generated by Django 3.2 on 2021-06-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='reason',
            field=models.TextField(max_length=300),
        ),
    ]
